import { Content, PortfolioItem } from './types';

// =================================================================
// 🟢 您的 LOGO 设置
// =================================================================
export const LOGO_URL = "https://i.postimg.cc/mrB5sdLw/LOGO.png"; 

export const CONTENT: Record<string, Content> = {
  zh: {
    nav: {
      home: "首页",
      services: "服务内容",
      portfolio: "精选案例",
      about: "关于我们",
      contact: "联系我们",
    },
    hero: {
      title: "海外华人空间的理想构建者",
      subtitle: "从设计图纸到落地交付。<span class=\"text-accent-red font-medium text-xl\">CJ Studio 诚嘉设计</span> 专注为欧洲及中国的客户提供高品质空间解决方案。我们不只是施工方，更是懂工艺的设计事务所，一切只为设计效果的完美呈现。",
      cta: "获取免费报价",
      experience: "14年从业经验 · 懂施工的设计团队",
      location: "服务地区：丹麦 / 瑞典 / 意大利 / 中国",
    },
    about: {
      title: "关于 CJ Studio (诚嘉设计)",
      description1: "CJ Studio 汇聚了感性的艺术视野与理性的工程思维。设计主理人 <span class=\"text-accent-red font-serif text-2xl mx-1\">沈忱 (Shen Chen)</span> 拥有14年行业履历，持有意大利 Unina DBE 建筑设计环境硕士学位。他的职业生涯横跨亚、欧、大洋洲：在新西兰从事过一线木作与全屋定制生产与安装，了解全木结构住宅施工工艺；在国内主持过展厅、商业综合体、别墅私宅及餐饮办公等多类型项目。作为“学院派”与“实干派”的结合，沈忱深谙从设计构思到施工落地的每一个细节。依托我们成熟的本地供应商体系，他致力于解决海外装修痛点，真正做到 <span class=\"text-accent-red font-medium text-lg border-b border-accent-red/30 pb-1\">“懂设计、懂工艺、懂落地”</span>，为您提供高品质的一站式交付。",
      description2: "市场主理人 <span class=\"text-accent-red font-serif text-2xl mx-1\">徐晨 (Chen Xu)</span> 常驻丹麦，作为一名活跃于欧洲的艺术家，他拥有深厚的艺术修养与极高的审美品味。他以敏锐的商业精英视角，精准洞察市场趋势与高端华人客户的生活方式需求，把控每一个项目的格调与品质。",
      stats: {
        years: "14+",
        yearsLabel: "从业经验",
        projects: "50+",
        projectsLabel: "落地案例",
      }
    },
    services: {
      title: "我们的服务",
      subtitle: "以设计效果为导向的全案服务，涵盖空间、产品与品牌视觉，确保从概念到实物的精准还原。",
      items: [
        {
          title: "商业空间全案设计",
          description: "涵盖餐厅、酒吧、零售店铺及办公空间。我们提供专业的动线规划与合规设计，助力商业价值最大化。",
          icon: "Commercial",
        },
        {
          title: "住宅与别墅室内设计",
          description: "专注别墅、大平层及私宅改造。提供从平面规划到全场景3D模拟的完整设计咨询，让家成为艺术与生活的结合。",
          icon: "Home",
        },
        {
          title: "家具产品设计",
          description: "提供原创家具研发与单品定制服务。无论是特殊尺寸的嵌入式柜体，还是具有艺术感的独立家具，我们都能设计并对接生产。",
          icon: "Furniture",
        },
        {
          title: "品牌视觉设计 (VI)",
          description: "为商业客户提供从LOGO、菜单到导视系统的全套视觉识别设计，确保空间风格与品牌形象的高度统一。",
          icon: "Branding",
        },
        {
          title: "软装搭配与改造",
          description: "基于预算提供灵活的软装方案。从宜家(IKEA)选品搭配到高端全屋定制资源对接，提升空间格调。",
          icon: "Cabinet",
        },
        {
          title: "设计落地与工程监理",
          description: "我们不是单纯的施工队，而是懂施工的设计师。提供关键节点巡查与工艺验收，严格把控施工质量，确保设计方案不走样。",
          icon: "Construction",
        },
      ],
    },
    portfolio: {
      title: "精选案例",
      subtitle: "实用主义与美学的平衡",
      viewProject: "查看项目详情",
      backToHome: "返回首页",
    },
    contact: {
      title: "联系我们",
      subtitle: "期待与您沟通您的项目",
      email: "电子邮箱",
      phone: "联系电话",
      wechat: "微信咨询",
      location: "工作室：丹麦 / 意大利 / 中国",
      linkedin: "https://www.linkedin.com/in/%E5%BF%B1-%E6%B2%88-117797a3/",
      formName: "您的称呼",
      formEmail: "联系方式 (电话/微信)",
      formMessage: "咨询内容 (如：餐厅装修、全屋定制)",
      formSubmit: "发送留言",
    },
  },
  en: {
    nav: {
      home: "Home",
      services: "Services",
      portfolio: "Portfolio",
      about: "About",
      contact: "Contact",
    },
    hero: {
      title: "Interior Design & Renovation Experts",
      subtitle: "From blueprints to reality. <span class=\"text-accent-red font-medium text-xl\">CJ Studio</span> is a design-driven firm serving clients in Europe and China. We go beyond construction—we are designers who master the craft of building, ensuring every detail serves the final aesthetic.",
      cta: "Get a Free Quote",
      experience: "14 Years Exp · Design-Led Build",
      location: "Serving: Denmark / Sweden / Italy / China",
    },
    about: {
      title: "About CJ Studio",
      description1: "CJ Studio represents the convergence of artistic vision and rational engineering. Design Principal <span class=\"text-accent-red font-serif text-2xl mx-1\">Shen Chen</span> brings 14 years of diverse international experience and holds a Master's degree in Architecture Design and Built Environment from Unina DBE, Italy. His expertise bridges theory and practice: he worked in New Zealand in frontline woodworking and custom furniture production & installation, mastering timber frame construction techniques, and has led a wide range of projects in China, including showrooms, commercial complexes, luxury villas, offices, and restaurants. This unique blend of architectural knowledge and craftsmanship allows him to masterfully control every detail from blueprint to construction. Backed by our mature supplier system, Shen ensures true <span class=\"text-accent-red font-medium text-lg border-b border-accent-red/30 pb-1\">'Design-to-Reality'</span> execution.",
      description2: "Market Principal <span class=\"text-accent-red font-serif text-2xl mx-1\">Chen Xu</span>, based in Denmark, is a distinguished Artist whose deep artistic background informs a refined aesthetic and keen market insight. As a business leader, he understands the lifestyle demands of the high-end Asian community, ensuring every project meets the highest standards of style and class.",
      stats: {
        years: "14+",
        yearsLabel: "Years Exp.",
        projects: "50+",
        projectsLabel: "Projects",
      }
    },
    services: {
      title: "Services",
      subtitle: "A design-driven approach covering space, product, and brand identity, ensuring precision from concept to reality.",
      items: [
        {
          title: "Commercial Space Design",
          description: "Restaurants, bars, retail shops, and offices. We provide professional layout planning and compliance design to maximize commercial value.",
          icon: "Commercial",
        },
        {
          title: "Residential & Villa Design",
          description: "Specialized in villas and apartments. We provide full design consulting from floor plans to 3D simulation, turning houses into artistic homes.",
          icon: "Home",
        },
        {
          title: "Furniture Product Design",
          description: "Original furniture development and custom bespoke pieces. From built-in cabinetry to artistic standalone furniture, we design and manage production.",
          icon: "Furniture",
        },
        {
          title: "Brand Visual Design (VI)",
          description: "Complete visual identity solutions including Logos, menus, and signage systems, ensuring your brand image aligns perfectly with the interior space.",
          icon: "Branding",
        },
        {
          title: "Styling & Soft Furnishing",
          description: "Flexible styling solutions based on your budget, ranging from curated IKEA selections to high-end custom resource procurement.",
          icon: "Cabinet",
        },
        {
          title: "Design Supervision & Build",
          description: "We are not just a construction crew; we are designers who understand construction. We provide site supervision and quality control to ensure the design is executed flawlessly.",
          icon: "Construction",
        },
      ],
    },
    portfolio: {
      title: "Selected Work",
      subtitle: "Balancing aesthetics with practicality",
      viewProject: "View Project",
      backToHome: "Back to Home",
    },
    contact: {
      title: "Contact Us",
      subtitle: "Let's discuss your project",
      email: "Email",
      phone: "Phone",
      wechat: "WeChat",
      location: "Studio: Denmark / Italy / China",
      linkedin: "https://www.linkedin.com/in/%E5%BF%B1-%E6%B2%88-117797a3/",
      formName: "Name",
      formEmail: "Contact (Phone/WeChat)",
      formMessage: "Message",
      formSubmit: "Send Message",
    },
  },
};

// =================================================================
// 🟢 案例列表
// =================================================================
export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  // 1. Vienna Villa, Austria
  {
    id: 16,
    title: "Vienna Villa, Austria",
    title_zh: "奥地利维也纳别墅",
    category: "Residential",
    description: "A comprehensive private villa design project located in Vienna, Austria. This project spans across three levels of luxury living space, including a grand living room, state-of-the-art kitchen, cozy children's suites, a peaceful study area, and a sophisticated master bedroom suite. The design harmonizes modern minimalism with the elegance of European living. Through precise spatial planning and meticulous material selection, we created a high-quality sanctuary that perfectly balances artistic aesthetics with daily functionality.",
    description_zh: "位于奥地利维也纳的豪华私人别墅全案设计。该项目涵盖了从一层到三层的完整生活空间规划，包含宏伟的客厅、现代化厨房、温馨的儿童房、静谧的书房以及精致的主卧套间。设计风格融合了现代极简与欧式生活的优雅，通过精密的平面布局与细腻的材质选配，为客户打造了一个兼具艺术审美与实用机能的高品质居所。",
    location: "Vienna, Austria",
    year: "2024",
    imageUrl: "https://i.postimg.cc/Cx1ngFk5/客厅1.jpg",
    gallery: [
      "https://i.postimg.cc/Cx1ngFk5/客厅1.jpg",
      "https://i.postimg.cc/bwBDYKRj/一层洗手间11.jpg",
      "https://i.postimg.cc/vZNg8pvs/一层洗手间12.jpg",
      "https://i.postimg.cc/DwZ4T2Ld/三层办公书房36.jpg",
      "https://i.postimg.cc/SxsYhyCV/三层办公书房37.jpg",
      "https://i.postimg.cc/Z5RvSTpw/三层办公书房38.jpg",
      "https://i.postimg.cc/K8z32ZBp/三层办公书房39.jpg",
      "https://i.postimg.cc/BnVLZdBz/三层卫生间40.jpg",
      "https://i.postimg.cc/7ZWGPpnd/三层卫生间41.jpg",
      "https://i.postimg.cc/t4MZRLzQ/三层卫生间42.jpg",
      "https://i.postimg.cc/13jnRLK1/三层卫生间43.jpg",
      "https://i.postimg.cc/jSFwqG4c/三层女儿房32.jpg",
      "https://i.postimg.cc/sgNQft4T/三层女儿房33.jpg",
      "https://i.postimg.cc/VkVrs3W7/三层女儿房34.jpg",
      "https://i.postimg.cc/4xS74rQL/三层女儿房35.jpg",
      "https://i.postimg.cc/Gm583ZxF/三层楼梯30.jpg",
      "https://i.postimg.cc/FHBdF2Vb/三层楼梯31.jpg",
      "https://i.postimg.cc/jjnWDZMp/主卧卫生间28.jpg",
      "https://i.postimg.cc/fbS3VBHn/主卧卫生间29.jpg",
      "https://i.postimg.cc/Z5MBY1LZ/主卧室22.jpg",
      "https://i.postimg.cc/mg5zZ0SZ/主卧室23.jpg",
      "https://i.postimg.cc/vmx143PR/主卧室24.jpg",
      "https://i.postimg.cc/k5RV2fjd/主卧衣帽间25.jpg",
      "https://i.postimg.cc/8CfF7tyD/主卧衣帽间26.jpg",
      "https://i.postimg.cc/GpTB4qMd/主卧衣帽间27.jpg",
      "https://i.postimg.cc/65z4g728/二层卫生间19.jpg",
      "https://i.postimg.cc/Dy54HWJb/二层卫生间20.jpg",
      "https://i.postimg.cc/Z5RvSTp5/二层卫生间21.jpg",
      "https://i.postimg.cc/htjQBSTP/二层走廊13.jpg",
      "https://i.postimg.cc/28TLMqbS/儿童书房10.jpg",
      "https://i.postimg.cc/4NwHqK74/儿童书房9.jpg",
      "https://i.postimg.cc/Yq8LZ4GK/儿童房14.jpg",
      "https://i.postimg.cc/5NpQTHYW/儿童房15.jpg",
      "https://i.postimg.cc/02ZKF6MP/儿童房16.jpg",
      "https://i.postimg.cc/02ZKF6M8/儿童房17.jpg",
      "https://i.postimg.cc/VL40pSrf/儿童房18.jpg",
      "https://i.postimg.cc/SxsYhyCz/入口玄关6.jpg",
      "https://i.postimg.cc/SxsYhyC9/入口玄关7.jpg",
      "https://i.postimg.cc/RZFJBMKc/入口玄关8.jpg",
      "https://i.postimg.cc/WbSqCDFV/厨房2.jpg",
      "https://i.postimg.cc/rwmRk8xz/楼梯44.jpg",
      "https://i.postimg.cc/RZFJBMK6/楼梯走廊4.jpg",
      "https://i.postimg.cc/cLHtSswt/楼梯走廊5.jpg",
      "https://i.postimg.cc/sDKGqBQR/餐厅3.jpg",
      "https://i.postimg.cc/ZYXJR4Gv/1F平面图.jpg",
      "https://i.postimg.cc/jqBR5tp7/2F平面图.jpg",
      "https://i.postimg.cc/44jXdsDh/3F平面图.jpg"
    ]
  },
  // 2. Austria Forest Bamboo Restaurant Design
  {
    id: 15,
    title: "Forest Bamboo Restaurant Austria",
    title_zh: "奥地利筑林餐厅设计",
    category: "Commercial",
    description: "An ambitious restaurant design project in Austria centered around the theme of 'Bamboo Forest'. This complex project features a variety of zones including a Moonlight Grove, a Bamboo Maze, specialized boat-shaped booths, and extensive outdoor dining areas. The design utilizes architectural axonometric drawings and floor plans to masterfully balance a high-volume buffet area with intimate, artistically-driven private dining experiences.",
    description_zh: "位于奥地利的大型餐饮设计项目，以“筑林”为核心主题。项目包含月光林地、竹迷宫区、特色的船形卡座以及广阔的户外就餐空间。通过精密的轴测图与平面规划，设计师成功地在高流量的自助取餐区与私密、极具艺术感的包间之间取得了平衡，营造出一种置身自然林间的沉浸式用餐体验。",
    location: "Austria",
    year: "2024",
    imageUrl: "https://i.postimg.cc/htHYLYtf/轴测图77.jpg",
    gallery: [
      "https://i.postimg.cc/htHYLYtf/轴测图77.jpg",
      "https://i.postimg.cc/X71mJqMr/休息区24.jpg",
      "https://i.postimg.cc/ZKs2RnkB/休息区27.jpg",
      "https://i.postimg.cc/Pf40gKSn/入口4.jpg",
      "https://i.postimg.cc/vB7CHvMM/包间25.jpg",
      "https://i.postimg.cc/hj8NP0gK/包间26.jpg",
      "https://i.postimg.cc/RF12VT9m/包间28.jpg",
      "https://i.postimg.cc/vT3j5H4Z/卡座53.jpg",
      "https://i.postimg.cc/HnBKbsr8/卡座54.jpg",
      "https://i.postimg.cc/zv0MTXyg/卡座沙发区31.jpg",
      "https://i.postimg.cc/tC48pPc1/卫生间66.jpg",
      "https://i.postimg.cc/Wb1xTryG/卫生间67.jpg",
      "https://i.postimg.cc/YqCTMgP1/卫生间68.jpg",
      "https://i.postimg.cc/TwvZ6s8p/备餐台44.jpg",
      "https://i.postimg.cc/nchNp7WF/外立面73.jpg",
      "https://i.postimg.cc/gk21mR7J/外立面74.jpg",
      "https://i.postimg.cc/sfcbkKTr/寿司吧49.jpg",
      "https://i.postimg.cc/Pf40gKSt/寿司吧50.jpg",
      "https://i.postimg.cc/445jDwWx/寿司吧51.jpg",
      "https://i.postimg.cc/28Sgrvt8/寿司吧52.jpg",
      "https://i.postimg.cc/yxv50YDB/就餐区35.jpg",
      "https://i.postimg.cc/Y0bVQqvM/就餐区37.jpg",
      "https://i.postimg.cc/c1mPpTXM/平面图69.jpg",
      "https://i.postimg.cc/y6P2Mnvr/平面图80.jpg",
      "https://i.postimg.cc/445jDwBQ/开放就餐区32.jpg",
      "https://i.postimg.cc/MT0gKYxf/户外1.jpg",
      "https://i.postimg.cc/yxVtJSYR/户外10.jpg",
      "https://i.postimg.cc/8c19FrPL/户外11.jpg",
      "https://i.postimg.cc/d3qp7Tt2/户外12.jpg",
      "https://i.postimg.cc/nrHgsQcK/户外13.jpg",
      "https://i.postimg.cc/brzWG2NH/户外14.jpg",
      "https://i.postimg.cc/qqkStCMw/户外15.jpg",
      "https://i.postimg.cc/pr249nXk/户外16.jpg",
      "https://i.postimg.cc/D02HWbyp/户外17.jpg",
      "https://i.postimg.cc/RhMy3nVs/户外18.jpg",
      "https://i.postimg.cc/J01vyB4d/户外19.jpg",
      "https://i.postimg.cc/ZRPXKLZy/户外2.jpg",
      "https://i.postimg.cc/Y0pZ4mqZ/户外20.jpg",
      "https://i.postimg.cc/qqkStCvf/户外21.jpg",
      "https://i.postimg.cc/vT3j5H4F/户外22.jpg",
      "https://i.postimg.cc/tTd8Czyx/户外3.jpg",
      "https://i.postimg.cc/85dxPbDR/户外5.jpg",
      "https://i.postimg.cc/G2P6hjrJ/户外6.jpg",
      "https://i.postimg.cc/FRbwsxmp/户外7.jpg",
      "https://i.postimg.cc/FRbwsxmx/户外8.jpg",
      "https://i.postimg.cc/D02HWbyX/户外9.jpg",
      "https://i.postimg.cc/X71mJqMF/月光林地47.jpg",
      "https://i.postimg.cc/qMDSRqfy/月光林地48.jpg",
      "https://i.postimg.cc/7Ytd6hvn/月光林地55.jpg",
      "https://i.postimg.cc/5NKT0ycm/月光林地56.jpg",
      "https://i.postimg.cc/hPZ6jvF2/月光林地57.jpg",
      "https://i.postimg.cc/J4Yvn0w6/月光林地58.jpg",
      "https://i.postimg.cc/pXc4TrN1/月光林地59.jpg",
      "https://i.postimg.cc/TYNFw18s/月光林地60.jpg",
      "https://i.postimg.cc/wjtPszHb/月光林地61.jpg",
      "https://i.postimg.cc/7ZCcT4Dd/月光林地62.jpg",
      "https://i.postimg.cc/8zF3rGNQ/月光林地63.jpg",
      "https://i.postimg.cc/DwWDbhnK/月光林地64.jpg",
      "https://i.postimg.cc/P5Lc8HTT/月光林地65.jpg",
      "https://i.postimg.cc/6pDPrPpZ/竹迷宫区36.jpg",
      "https://i.postimg.cc/W1QyGy1M/竹迷宫区38.jpg",
      "https://i.postimg.cc/sgtLYLgJ/竹迷宫区39.jpg",
      "https://i.postimg.cc/dVzf2fVn/竹迷宫区40.jpg",
      "https://i.postimg.cc/bwK5x5wg/竹迷宫区41.jpg",
      "https://i.postimg.cc/qv9FsFvj/竹迷宫区42.jpg",
      "https://i.postimg.cc/d0rx49h8/竹迷宫区43.jpg",
      "https://i.postimg.cc/ZqpMVLWQ/竹迷宫区45.jpg",
      "https://i.postimg.cc/d0rx49hg/竹迷宫区46.jpg",
      "https://i.postimg.cc/PqYR2MLs/自助取餐区33.jpg",
      "https://i.postimg.cc/ZqpMVL9S/自助取餐区34.jpg",
      "https://i.postimg.cc/qRcWMG0g/船卡座29.jpg",
      "https://i.postimg.cc/tTd8CzyZ/船卡座30.jpg",
      "https://i.postimg.cc/9Q4Sq2Cm/轴测图70.jpg",
      "https://i.postimg.cc/0yL4Y4yP/轴测图71.jpg",
      "https://i.postimg.cc/htHYLYtD/轴测图72.jpg",
      "https://i.postimg.cc/13LdGd3z/轴测图75.jpg",
      "https://i.postimg.cc/RZjY7YZF/轴测图76.jpg",
      "https://i.postimg.cc/2SPtQtSy/轴测图78.jpg",
      "https://i.postimg.cc/2SPtQtSL/轴测图79.jpg",
      "https://i.postimg.cc/7hmcSY5r/酒吧台23.jpg"
    ]
  },
  // 3. Tuscany Livorno Mini Hotel
  {
    id: 14,
    title: "Tuscany Livorno Mini Hotel",
    title_zh: "托斯卡纳Livorno Mini Hotel",
    category: "Commercial",
    description: "A boutique hotel design project located in Livorno, Italy. The concept seamlessly blends vintage elegance with contemporary comfort. The scope of work includes a sophisticated lobby reception area, artistically curated guest rooms, atmospheric corridors, and a signature music bar. By precisely controlling light and shadow layers alongside high-quality textures, we have created a refined sanctuary where guests can relax and immerse themselves in the charm of modern Italian design.",
    description_zh: "位于意大利里窝那（Livorno）的精品酒店设计项目。设计巧妙融合了复古优雅与现代舒适感。项目涵盖了大气考究的大堂接待区、充满艺术感的客房、具有独特氛围的走廊以及融合音乐元素的特色酒吧。通过对光影层次的精准把控 and 高质感材质的运用，为旅人营造出一个既能放松身心又能感受意式设计魅力的精致旅居之所。",
    location: "Livorno, Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/KjNfCqbf/大堂9.jpg",
    gallery: [
      "https://i.postimg.cc/KjNfCqbf/大堂9.jpg",
      "https://i.postimg.cc/J0qxS68K/大堂10.jpg",
      "https://i.postimg.cc/0jfnhWvV/大堂11.jpg",
      "https://i.postimg.cc/gjDs1SpB/大堂12.jpg",
      "https://i.postimg.cc/Wzn8xWV9/大堂8.jpg",
      "https://i.postimg.cc/QNkfBt7M/客房_1.jpg",
      "https://i.postimg.cc/CMHcZ18n/客房_2.jpg",
      "https://i.postimg.cc/NG7dyMXm/客房_3.jpg",
      "https://i.postimg.cc/gcqgwJhv/客房_4.jpg",
      "https://i.postimg.cc/wxcwtvNc/客房_5.jpg",
      "https://i.postimg.cc/Kcr0KzTP/客房_6.jpg",
      "https://i.postimg.cc/59qsH0zm/客房_7.jpg",
      "https://i.postimg.cc/fWj83LdK/客房_8.jpg",
      "https://i.postimg.cc/3rCtyRGn/客房_9.jpg",
      "https://i.postimg.cc/DfdxWZGC/客房走廊13.jpg",
      "https://i.postimg.cc/3rCtyRGS/客房走廊14.jpg",
      "https://i.postimg.cc/TYdCn6j9/客房走廊15.jpg",
      "https://i.postimg.cc/NfspRc8d/客房走廊16.jpg",
      "https://i.postimg.cc/02kc7sGB/客房走廊17.jpg",
      "https://i.postimg.cc/m2L87s3J/客房走廊18.jpg",
      "https://i.postimg.cc/tCBD5M2q/走廊_1.jpg",
      "https://i.postimg.cc/X7sx8zQX/走廊_2.jpg",
      "https://i.postimg.cc/Nfdb4zpF/走廊_3.jpg",
      "https://i.postimg.cc/RhRd2smj/酒吧_1.jpg",
      "https://i.postimg.cc/D0g6Rjh9/酒吧_2.jpg",
      "https://i.postimg.cc/MHD5gPxk/酒吧_3.jpg",
      "https://i.postimg.cc/MZb9cTBW/酒吧_4.jpg",
      "https://i.postimg.cc/gcqgwJhj/酒吧_5.jpg",
      "https://i.postimg.cc/c1MFKH3H/酒吧_6.jpg",
      "https://i.postimg.cc/RVSXwBQB/音乐酒吧1.jpg",
      "https://i.postimg.cc/02VZfBZh/音乐酒吧2.jpg",
      "https://i.postimg.cc/J4pKq2K9/音乐酒吧3.jpg",
      "https://i.postimg.cc/8PZwH0w2/音乐酒吧4.jpg",
      "https://i.postimg.cc/dt5nBx4c/音乐酒吧5.jpg",
      "https://i.postimg.cc/15vMHjJs/音乐酒吧5b.jpg",
      "https://i.postimg.cc/Yqd83sbt/音乐酒吧6.jpg",
      "https://i.postimg.cc/15vMHjJR/音乐酒吧7.jpg"
    ]
  },
  // 4. Lucio Minimalist Apartment in Rome
  {
    id: 13,
    title: "Lucio Minimalist Apartment in Rome",
    title_zh: "罗马Lucio极简公寓",
    category: "Residential",
    description: "A minimalist apartment renovation project in Rome. The design emphasizes clean architectural lines and an integrated storage system, particularly featured in the custom entryway cabinetry. This project reflects our expertise in optimizing urban layouts through detailed technical drawings, including floor plans and elevations, to achieve a pure and functional aesthetic.",
    description_zh: "位于罗马的Lucio极简公寓翻新项目。该设计核心在于纯净的建筑线条与强大的收纳系统，通过定制化的玄关一体柜设计，将美学与实用机能完美融合。项目展示了精细的平面规划与立面设计逻辑，是现代都市极简生活的范本。",
    location: "Rome, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/prTRnSsy/平面图12.jpg",
    gallery: [
      "https://i.postimg.cc/prTRnSsy/平面图12.jpg",
      "https://i.postimg.cc/prTRnSsm/入口玄关1.jpg",
      "https://i.postimg.cc/vTBb6K0g/入口玄关2.jpg",
      "https://i.postimg.cc/3NRYDqtJ/客厅11.jpg",
      "https://i.postimg.cc/vBXGTytY/客厅3.jpg",
      "https://i.postimg.cc/nzTnrxGV/客厅4.jpg",
      "https://i.postimg.cc/0QZ9jv02/客厅6.jpg",
      "https://i.postimg.cc/bJLqrP9Z/客厅7.jpg",
      "https://i.postimg.cc/Vv6mbhKC/玄关一体柜8.jpg",
      "https://i.postimg.cc/yxdsSGL9/玄关一体柜9.jpg",
      "https://i.postimg.cc/90MCqkL9/玄关柜10.jpg",
      "https://i.postimg.cc/RFGvhmLv/电视柜5.jpg",
      "https://i.postimg.cc/C51Sf2cF/立面13.jpg",
      "https://i.postimg.cc/rsmMtHfw/立面14.jpg",
      "https://i.postimg.cc/kG4qtHT4/立面15.jpg",
      "https://i.postimg.cc/x8CnbZ68/立面16.jpg"
    ]
  },
  // 5. Vienna YYDS Zodiac Art Restaurant
  {
    id: 12,
    title: "Vienna YYDS Zodiac Art Restaurant",
    title_zh: "维也纳YYDS星座艺术餐厅改造",
    category: "Commercial",
    description: "A transformative renovation project in Vienna, Austria. This unique dining space blends celestial zodiac themes with avant-garde artistic salon elements. The design features a dramatic main entrance, an integrated bar area, and specialized 'Zodiac' dining zones. Through the use of bold textures, layered lighting, and sculptural seating, we created an immersive artistic lounge that serves as both a high-end restaurant and a cultural hub.",
    description_zh: "位于奥地利维也纳的餐厅改造项目。该设计将神秘的星座主题与前卫的艺术沙龙元素巧妙结合。项目包含极具仪式感的主入口、多功能吧台区以及极具特色的“星座”主题就餐区。通过大胆的材质碰撞、层次丰富的灯光设计以及雕塑感的卡座空间，打造出一个兼具高端餐饮与文化沙龙功能的沉浸式艺术空间。",
    location: "Vienna, Austria",
    year: "2024",
    imageUrl: "https://i.postimg.cc/kgNP19R5/艺术沙龙_11.jpg",
    gallery: [
      "https://i.postimg.cc/kgNP19R5/艺术沙龙_11.jpg",
      "https://i.postimg.cc/hGSWNwVT/主入口_1.jpg",
      "https://i.postimg.cc/wB68nPDJ/主入口_2.jpg",
      "https://i.postimg.cc/qvcHb0hS/休息台阶_3.jpg",
      "https://i.postimg.cc/dVcKjD14/卡座区_5.jpg",
      "https://i.postimg.cc/rw2LNzmY/吧区_4.jpg",
      "https://i.postimg.cc/6pxNfT3M/星座就餐区_6.jpg",
      "https://i.postimg.cc/T3B59Vbr/星座就餐区_7.jpg",
      "https://i.postimg.cc/y8hCQBgp/星座就餐区_8.jpg",
      "https://i.postimg.cc/Nj8vJY9V/星座就餐区_9.jpg",
      "https://i.postimg.cc/1301CPnb/艺术沙龙_10.jpg",
      "https://i.postimg.cc/TPRMBSnx/艺术沙龙_12.jpg",
      "https://i.postimg.cc/XvVSth9j/艺术沙龙_13.jpg",
      "https://i.postimg.cc/TPRMBSnf/艺术沙龙_14.jpg",
      "https://i.postimg.cc/hGSWNwVJ/艺术沙龙_15.jpg"
    ]
  },
  // 6. Villa in Turin
  {
    id: 11,
    title: "Villa in Turin",
    title_zh: "都灵别墅",
    category: "Residential",
    description: "A mid-to-high-end residential renovation in Turin. Avoiding ostentatious luxury, the design focuses on modern practicality and comfort. We optimized the spatial layout and lighting to create a simple, elegant, and warm atmosphere tailored for daily living.",
    description_zh: "位于都灵的住宅翻新项目，定位为中高端现代居所。设计摒弃了繁复奢华的堆砌，转而专注于现代生活的舒适性与实用机能。通过对空间布局的梳理与光影氛围的营造，打造出一个简约、雅致且充满生活温度的家。",
    location: "Turin, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/jdMVRbVV/GF场景_2.png",
    gallery: [
      "https://i.postimg.cc/jdMVRbVV/GF场景_2.png",
      "https://i.postimg.cc/rFf6qLB7/GF场景_1.png",
      "https://i.postimg.cc/gjG5PMNL/GF场景_10.png",
      "https://i.postimg.cc/3N36HLnh/GF场景_11.png",
      "https://i.postimg.cc/5yfGMPn1/GF场景_12.png",
      "https://i.postimg.cc/x897Sst1/GF场景_13.png",
      "https://i.postimg.cc/MZYNYSpn/GF场景_14.png",
      "https://i.postimg.cc/Prrc3RCz/GF场景_15_1.png",
      "https://i.postimg.cc/qBGSGTvh/GF场景_16.png",
      "https://i.postimg.cc/66hghXpd/GF场景_17.png",
      "https://i.postimg.cc/fTTF2r3n/GF场景_18.png",
      "https://i.postimg.cc/3JJ6ScyT/GF场景_19.png",
      "https://i.postimg.cc/jdg1G4NT/GF场景_20.png",
      "https://i.postimg.cc/FsW62VcF/GF场景_21.png",
      "https://i.postimg.cc/TY7sZJm5/GF场景_22.png",
      "https://i.postimg.cc/FsW62VcL/GF场景_23.png",
      "https://i.postimg.cc/Gm4frTJ4/GF场景_24.png",
      "https://i.postimg.cc/y8DGB3Xn/GF场景_25.png",
      "https://i.postimg.cc/HkrNH846/GF场景_26.png",
      "https://i.postimg.cc/15vxyQx4/GF场景_3.png",
      "https://i.postimg.cc/wTwK9pKB/GF场景_4.png",
      "https://i.postimg.cc/qRsYSfc1/GF场景_5.png",
      "https://i.postimg.cc/HxDR6WMt/GF场景_6.png",
      "https://i.postimg.cc/xCv7hrGR/GF场景_7.png",
      "https://i.postimg.cc/HxwKRG0t/GF场景_8.png",
      "https://i.postimg.cc/vBrjkRLY/GF场景_9.png"
    ]
  },
  // 7. Turin Steakhouse
  {
    id: 18,
    title: "Turin Steakhouse",
    title_zh: "都灵牛排馆",
    category: "Commercial",
    description: "A comprehensive steakhouse design project in Turin, Italy. The project masterfully utilizes basement space, featuring a small performance stage and an expansive dining area to create a unique social and entertainment atmosphere. The design covers everything from the sophisticated exterior facade and window displays to the interior bar, detailed screen partitions, and wine cellar displays. Through curated lighting and high-quality material textures, we created a stylish and modern Italian dining destination.",
    description_zh: "位于意大利都灵的大型牛排馆设计。项目巧妙地利用了地下室空间，设置了小舞台与开阔的就餐区，营造出独特的社交与演艺氛围。设计涵盖了从精致的外立面、橱窗设计到内部的酒吧台、屏风细节及酒柜陈列。通过对光影的精心布置与材质的质感表现，打造出一个极具格调的现代意式餐饮空间。",
    location: "Turin, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/Y0RVQNXq/地下室就餐区28.jpg",
    gallery: [
      "https://i.postimg.cc/Y0RVQNXq/地下室就餐区28.jpg",
      "https://i.postimg.cc/CM76PNNf/一层22.jpg",
      "https://i.postimg.cc/J7xd6qqZ/一层23.jpg",
      "https://i.postimg.cc/Wb4YQkWf/一层29.jpg",
      "https://i.postimg.cc/y8Mfgr14/一层收银台21.jpg",
      "https://i.postimg.cc/g2CMXBYS/一层楼梯厅33.jpg",
      "https://i.postimg.cc/Z5GfBDTX/一层楼梯厅34.jpg",
      "https://i.postimg.cc/Nf0CWHJn/一层橱窗24.jpg",
      "https://i.postimg.cc/TYPNZD7Z/一层橱窗25.jpg",
      "https://i.postimg.cc/xTdpWzxw/一层橱窗26.jpg",
      "https://i.postimg.cc/x1JxdSSL/一层酒吧台30.jpg",
      "https://i.postimg.cc/zGsdbPJF/一层酒吧台31.jpg",
      "https://i.postimg.cc/Dw9CJY2g/一层酒吧台32.jpg",
      "https://i.postimg.cc/KjfVt79x/地下室小舞台5.jpg",
      "https://i.postimg.cc/HsSRx2cz/地下室小舞台6.jpg",
      "https://i.postimg.cc/jS2VQ9Yn/地下室就餐区10.jpg",
      "https://i.postimg.cc/t4J0tfGx/地下室就餐区12.jpg",
      "https://i.postimg.cc/6pmkH0BV/地下室就餐区13.jpg",
      "https://i.postimg.cc/BnVrhgJw/地下室就餐区14.jpg",
      "https://i.postimg.cc/jjnGB7jH/地下室就餐区17.jpg",
      "https://i.postimg.cc/TP5ZBDPc/地下室就餐区18.jpg",
      "https://i.postimg.cc/XvBTtCvR/地下室就餐区19.jpg",
      "https://i.postimg.cc/zv86L2Fd/地下室就餐区20.jpg",
      "https://i.postimg.cc/1Xs2g7Kz/地下室就餐区27.jpg",
      "https://i.postimg.cc/zGcsdjqX/地下室就餐区7.jpg",
      "https://i.postimg.cc/T34zk9T2/地下室就餐区8.jpg",
      "https://i.postimg.cc/6qMj8W34/外立面1.jpg",
      "https://i.postimg.cc/gjgSxzJh/外立面2.jpg",
      "https://i.postimg.cc/59gk733c/外立面3.jpg",
      "https://i.postimg.cc/1RBYCHHf/外立面4.jpg",
      "https://i.postimg.cc/vTY28gQd/屏风细节设计35.jpg",
      "https://i.postimg.cc/q7K51HmS/楼梯35.jpg",
      "https://i.postimg.cc/C1H6VHpC/楼梯36.jpg",
      "https://i.postimg.cc/TwqHXqv4/楼梯37.jpg",
      "https://i.postimg.cc/1tcYZc12/楼梯38.jpg",
      "https://i.postimg.cc/cCxk1gdP/楼梯39.jpg",
      "https://i.postimg.cc/x8fpjJ0N/楼梯40.jpg",
      "https://i.postimg.cc/0jVWzkQj/楼梯41.jpg",
      "https://i.postimg.cc/qvzYC322/楼梯9.jpg",
      "https://i.postimg.cc/QNmn4bbF/细节11.jpg",
      "https://i.postimg.cc/dVLXTyGt/酒柜细节15.jpg",
      "https://i.postimg.cc/vZcj6V5c/酒柜细节16.jpg"
    ]
  },
  // 8. Piedmont Bar Sociale Renovation
  {
    id: 19,
    title: "Piedmont Bar Sociale Renovation",
    title_zh: "皮埃蒙特Bar sociale改造",
    category: "Commercial",
    description: "A social bar renovation project in Piedmont, Italy. While preserving the original social core of the community space, the design introduces a contemporary aesthetic and renewed vitality. The project includes a complete reconfiguration of the bar counter area, a strategic lighting layout, and a curated selection of materials to create a welcoming yet modern hub for social interaction.",
    description_zh: "位于意大利皮埃蒙特的Bar sociale改造项目。设计师通过现代的设计手法，在保留原有社区社交属性的基础上，赋予空间全新的生命力与审美深度。项目涵盖了内部吧台区的重构、灯光的重新布局以及材质的精细选择，打造出一个兼具温馨氛围与现代格调的社区交流中心。",
    location: "Piedmont, Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/MHswz88x/11.jpg",
    gallery: [
      "https://i.postimg.cc/MHswz88x/11.jpg",
      "https://i.postimg.cc/FzFmtH8P/1.jpg",
      "https://i.postimg.cc/nrdxnttb/10.jpg",
      "https://i.postimg.cc/D0Ch7KKh/12.jpg",
      "https://i.postimg.cc/1XWSyZZs/13.jpg",
      "https://i.postimg.cc/G3zdFvT9/14.jpg",
      "https://i.postimg.cc/KcQxPt31/15.jpg",
      "https://i.postimg.cc/WzpjR1CS/2.jpg",
      "https://i.postimg.cc/C5MYyxXm/3.jpg",
      "https://i.postimg.cc/SRQq0x3g/4.jpg",
      "https://i.postimg.cc/j28TRrYc/5.jpg",
      "https://i.postimg.cc/sxnz3RCT/6.jpg",
      "https://i.postimg.cc/1XWSyZ1W/7.jpg",
      "https://i.postimg.cc/6qHKBNxb/8.jpg",
      "https://i.postimg.cc/0jtv9q1B/9.jpg"
    ]
  },
  // 9. Villa in Tuscany (Prato)
  {
    id: 6,
    title: "Villa in Tuscany",
    title_zh: "托斯卡纳别墅",
    category: "Residential",
    description: "A newly constructed timber-frame villa in Prato. While retaining the original structural integrity, we elevated the standard developer finishing through refined interior design and soft furnishings. The project transforms a standardized architectural shell into a bespoke living space with unique aesthetic quality.",
    description_zh: "位于普拉托（Prato）的一栋新建木结构别墅。项目在保留原建筑主体木结构的基础上，突破了意大利标准交付的普通装修模式。我们通过精细化的室内设计干预与软装陈设，重新定义了空间的审美与质感，将一个标准化的建筑外壳转化为具有独特生活格调的居住空间。",
    location: "Prato, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/KYhT0C0f/base_1.png",
    gallery: [
      "https://i.postimg.cc/KYhT0C0f/base_1.png",
      "https://i.postimg.cc/xdGfnZnp/GF场景_10.png",
      "https://i.postimg.cc/GpPLdfdV/GF场景_11.png",
      "https://i.postimg.cc/8CdpNYTV/GF场景_12.png",
      "https://i.postimg.cc/90kVL5YR/GF场景_14.png",
      "https://i.postimg.cc/prSxsbJG/GF场景_16.png",
      "https://i.postimg.cc/Dfp2vL3k/GF场景_18.png",
      "https://i.postimg.cc/0j4xVR0c/GF场景_19.png",
      "https://i.postimg.cc/9FvCT2Mj/GF场景_20.png",
      "https://i.postimg.cc/W4mNTyTQ/GF场景_9.png",
      "https://i.postimg.cc/fbss2vmX/场景_1.png",
      "https://i.postimg.cc/wBkpSsk6/场景_2.png",
      "https://i.postimg.cc/ZqLS1yLY/场景_4.png",
      "https://i.postimg.cc/635Xw5Hb/场景_5.png",
      "https://i.postimg.cc/pTGtdb42/场景_8.png",
      "https://i.postimg.cc/1X84mKWn/base_10.png",
      "https://i.postimg.cc/d1HLcf9h/base_11.png",
      "https://i.postimg.cc/mkPhLSdX/base_12.png",
      "https://i.postimg.cc/vZFDyf5Z/base_13.png",
      "https://i.postimg.cc/L8KhSLjY/base_14.png",
      "https://i.postimg.cc/QNzH6Rt1/base_15.png",
      "https://i.postimg.cc/2jtVHP6g/base_16.png",
      "https://i.postimg.cc/Wbt0zGFv/base_2.png",
      "https://i.postimg.cc/VLTnCJnQ/base_3.png",
      "https://i.postimg.cc/wT3DMXy6/base_4.png",
      "https://i.postimg.cc/Y00L47SR/base_5.png",
      "https://i.postimg.cc/tJcZWc1f/base_6.png",
      "https://i.postimg.cc/3Nq4mqyV/base_7.png",
      "https://i.postimg.cc/v826J4Ph/base_8.png",
      "https://i.postimg.cc/W3Whcy74/base_9.png"
    ]
  },
  // 10. Zen Sushi Restaurant
  {
    id: 3,
    title: "Zen Sushi Restaurant",
    title_zh: "Zen Sushi 寿司餐厅",
    category: "Commercial",
    description: "A serene sushi dining space designed with minimal aesthetics. We utilized light wood textures, traditional dividers, and soft lighting to create a calm Zen atmosphere.",
    location: "Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/x1DjVbkV/场景_2.png",
    gallery: [
      "https://i.postimg.cc/x1DjVbkV/场景_2.png",
      "https://i.postimg.cc/VkqffLM5/场景_1.png",
      "https://i.postimg.cc/DybfNcwd/场景_3.png",
      "https://i.postimg.cc/65G6Phpv/场景_4.png",
      "https://i.postimg.cc/NMMBk6nR/场景_5.png",
      "https://i.postimg.cc/G90RRZmk/场景_6.png",
      "https://i.postimg.cc/4nCGGrxY/场景_7.png",
      "https://i.postimg.cc/bY4SdrGW/场景_8.png",
      "https://i.postimg.cc/9f9n5rqJ/场景_11.png",
      "https://i.postimg.cc/FKSB57Jy/场景_12.png",
      "https://i.postimg.cc/Z52MMr04/场景_13.png",
      "https://i.postimg.cc/q7K5VzCL/场景_14.png"
    ]
  },
  // 11. Udine Steakhouse
  {
    id: 2,
    title: "Udine Steakhouse",
    title_zh: "Udine 牛排馆",
    category: "Commercial",
    description: "A comprehensive interior design for a modern steakhouse in Udine. The project features a robust spatial layout including detailed isometric views and floor plans, ensuring a seamless flow between the kitchen and dining areas.",
    location: "Udine, Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/Hsf0G34m/场景_1.png",
    gallery: [
      "https://i.postimg.cc/Hsf0G34m/场景_1.png",
      "https://i.postimg.cc/wTt5bnJd/场景_2.png",
      "https://i.postimg.cc/WbQmRSmx/场景_3.png",
      "https://i.postimg.cc/28PdpTF5/场景_4.png",
      "https://i.postimg.cc/rmnWf9Fb/场景_5.png",
      "https://i.postimg.cc/j5gNMhSV/场景_6.png",
      "https://i.postimg.cc/Px3ZSMr9/场景_7.png",
      "https://i.postimg.cc/3RSptZJs/场景_8.png",
      "https://i.postimg.cc/xTtCMd8t/iso.jpg",
      "https://i.postimg.cc/jdZ5Pj2v/plan.jpg"
    ]
  },
  // 12. Sushi Nami
  {
    id: 1,
    title: "Sushi Nami",
    title_zh: "Sushi Nami",
    category: "Commercial",
    description: "A complete renovation of a 200sqm Asian fusion restaurant. We focused on warm lighting and durable materials to create a welcoming atmosphere while adhering to strict local hygiene regulations.",
    location: "Milan, Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/tJpdcght/场景_10.jpg",
    gallery: [
      "https://i.postimg.cc/tJpdcght/场景_10.jpg",
      "https://i.postimg.cc/J0M3FhbX/场景_5.jpg",
      "https://i.postimg.cc/QChgzMp1/场景_6.jpg",
      "https://i.postimg.cc/rsMGHpSG/场景_9.jpg",
      "https://i.postimg.cc/GtdPfpkt/场景_1.jpg",
      "https://i.postimg.cc/D0nQNzqZ/场景_2.jpg"
    ]
  },
  {
    id: 4,
    title: "C&B Nail Salon",
    title_zh: "C&B 美甲沙龙",
    category: "Commercial",
    description: "A sophisticated nail salon design featuring warm wood textures, custom polish display shelving, and ergonomic pedicure stations.",
    location: "Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/q7BSVmQd/场景_1.png", 
    gallery: [
      "https://i.postimg.cc/q7BSVmQd/场景_1.png",
      "https://i.postimg.cc/RZLyYr1z/场景_2.png",
      "https://i.postimg.cc/13r2dx0z/场景_3.png",
      "https://i.postimg.cc/SN0PNQDN/场景_7.png",
      "https://i.postimg.cc/HsQhJGh4/场景_8.png",
      "https://i.postimg.cc/y8Ln97hw/场景_9.png"
    ]
  },
  {
    id: 5,
    title: "Numidio Apartment in Rome",
    title_zh: "罗马Numidio公寓项目",
    category: "Residential",
    description: "A contemporary apartment renovation in the Numidio district of Rome. This project harmonizes functional spatial planning with a warm, minimalist aesthetic. Through the use of soft textures, integrated lighting, and a neutral color palette, we transformed this urban dwelling into a serene sanctuary that balances modern Italian style with daily practicality.",
    description_zh: "位于罗马Numidio区域的现代公寓翻新项目。该设计将功能性的空间规划与温润的极简主义美学相融合。通过柔和的材质触感、内嵌式灯光设计以及中性色调的运用，我们将这处都市居所打造为一个宁静的避风港，完美平衡了现代意式格调与生活实用性。",
    location: "Rome, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/T3Mt4Dnr/主卧_1.jpg",
    gallery: [
      "https://i.postimg.cc/T3Mt4Dnr/主卧_1.jpg",
      "https://i.postimg.cc/VkQKVCXW/主卧_2.jpg",
      "https://i.postimg.cc/GmFXwmjT/主卧_3.jpg",
      "https://i.postimg.cc/RZ7g5ZTf/主卧_4.jpg",
      "https://i.postimg.cc/Z58wt5Lc/主卧_5.jpg",
      "https://i.postimg.cc/BnTm9nCC/主卧_6.jpg",
      "https://i.postimg.cc/02JtnfKN/卫生间_1.jpg",
      "https://i.postimg.cc/QdGfyTcZ/卫生间_2.jpg",
      "https://i.postimg.cc/52dsRC8J/卫生间_3.jpg",
      "https://i.postimg.cc/hvN2gJw9/厨房_1.jpg",
      "https://i.postimg.cc/tJ8By1fz/厨房_2.jpg",
      "https://i.postimg.cc/Vv2K1STR/厨房_3.jpg",
      "https://i.postimg.cc/NFZdYyV6/厨房_4.jpg",
      "https://i.postimg.cc/bY5C1MJ1/客厅_1.jpg",
      "https://i.postimg.cc/1RdCDTtr/客厅_2.jpg",
      "https://i.postimg.cc/dQfHGX16/客厅_3.jpg",
      "https://i.postimg.cc/sfL658Xw/客厅_4.jpg",
      "https://i.postimg.cc/nVWRq5z5/客厅_5.jpg",
      "https://i.postimg.cc/J4BTxqH4/客厅_6.jpg",
      "https://i.postimg.cc/vTC0M1jp/次卧_1.jpg",
      "https://i.postimg.cc/mkKmRcJf/次卧_2.jpg",
      "https://i.postimg.cc/6qFMw7gx/次卧_3.jpg",
      "https://i.postimg.cc/Rh2g93yB/次卧_4.jpg"
    ]
  },
  {
    id: 7,
    title: "The B Place Cola B&B",
    title_zh: "罗马梵蒂冈民宿The B Place Cola",
    category: "Commercial",
    description: "A luxury B&B design located near the Vatican in Rome. Each room features a unique high-fashion theme, including Andy Warhol, Gucci, Tiffany, Hermes, and Chanel. The design merges iconic brand aesthetics with high-end hospitality to create an immersive, boutique lodging experience.",
    description_zh: "位于罗马梵蒂冈附近的精品民宿设计项目。空间以“时尚艺术”为核心主题，精心打造了包括安迪·沃霍尔（Andy Warhol）、古驰（Gucci）、蒂芙尼（Tiffany）、爱马仕（Hermes）及香奈儿（Chanel）在内的多个主题客房。设计将经典品牌美学与高端酒店功能相融合，为住客提供极具沉浸感的意式艺术旅居体验。",
    location: "Rome (Vatican), Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/Gh7yBwmn/Andy_Warhol_Room_25.png",
    gallery: [
      "https://i.postimg.cc/Gh7yBwmn/Andy_Warhol_Room_25.png",
      "https://i.postimg.cc/Qx4TBGdD/Andy_Warhol_Room_26.png",
      "https://i.postimg.cc/rFnrdXwk/Andy_Warhol_Room_27.png",
      "https://i.postimg.cc/c49nKyLq/Andy_Warhol_Room_28.png",
      "https://i.postimg.cc/RVsH35Zh/Andy_Warhol_Room_29.png",
      "https://i.postimg.cc/sD6hBdgB/Andy_Warhol_Room_30.png",
      "https://i.postimg.cc/4xYhVLYc/GUCCI_Room_18.png",
      "https://i.postimg.cc/fRV0m2V0/GUCCI_Room_19.png",
      "https://i.postimg.cc/bwZ2kCZH/GUCCI_Room_20.png",
      "https://i.postimg.cc/T3B59Vbr/GUCCI_Room_21.png",
      "https://i.postimg.cc/Vk20RqtX/Tiffany_Room_7.png",
      "https://i.postimg.cc/52DQ3Bzg/Tiffany_Room_8.png",
      "https://i.postimg.cc/QdvKbQ7S/Tiffany_Room_9.png",
      "https://i.postimg.cc/TPmLHKqg/公共休息区_1.png",
      "https://i.postimg.cc/3wp4bkC2/公共休息区_2.png",
      "https://i.postimg.cc/JnLDwRPj/公共休息区_4.png",
      "https://i.postimg.cc/s2SQ0M9d/公共区域_24.png",
      "https://i.postimg.cc/y823Pm9C/爱马仕Room_14.png",
      "https://i.postimg.cc/mgK1wYMf/爱马仕Room_15.png",
      "https://i.postimg.cc/SxHYr680/爱马仕Room_16.png",
      "https://i.postimg.cc/FHwkZyc9/爱马仕Room_17.png",
      "https://i.postimg.cc/PxQLT07j/走廊_22.png",
      "https://i.postimg.cc/PJfCx2GH/走廊_23.png",
      "https://i.postimg.cc/1trgsbjL/走廊_3.png",
      "https://i.postimg.cc/prVmTqNH/走廊_5.png",
      "https://i.postimg.cc/qqBNRjf4/走廊_6.png",
      "https://i.postimg.cc/9MhR3cJd/香奈尔Room_10.png",
      "https://i.postimg.cc/RFB6rvXD/香奈尔Room_11.png",
      "https://i.postimg.cc/bJhDXq3V/香奈尔Room_12.png",
      "https://i.postimg.cc/zBFL84c0/香奈尔Room_13.png"
    ]
  },
  {
    id: 8,
    title: "Nettuno Duplex Apartment",
    title_zh: "罗马nettuno叠层公寓",
    category: "Residential",
    description: "A high-end duplex apartment renovation in Nettuno, Rome. Spanning from the basement to the second floor, this project meticulously reconfigures the spatial layout to create a sophisticated modern Italian living experience. The design focuses on material textures, layered lighting transitions, and optimized functional spaces.",
    description_zh: "位于罗马内图诺（Nettuno）的高端叠层公寓设计。项目涵盖地下一层至地上二层，通过对空间的精细化拆解与重构，营造出一种低调而奢华的现代意式生活氛围。设计重点在于材质的质感表达、光影的层次过渡以及功能空间的极致利用。",
    location: "Rome (Nettuno), Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/SNDKZWB1/一层客厅电视背景墙.png",
    gallery: [
      "https://i.postimg.cc/SNDKZWB1/一层客厅电视背景墙.png",
      "https://i.postimg.cc/T3NpPrQb/B1层主卧.jpg",
      "https://i.postimg.cc/0yXbNpZD/B1层主卧_2.jpg",
      "https://i.postimg.cc/dVNL08n8/B1层主卧_3.jpg",
      "https://i.postimg.cc/q7tg6zZh/B1层主卧床头背景.jpg",
      "https://i.postimg.cc/tg17nYm6/B1层主卧衣帽间_1.jpg",
      "https://i.postimg.cc/43KnHmFV/B1层主卧衣帽间_2.jpg",
      "https://i.postimg.cc/6Q7T4y1r/B1层主卧衣帽间_3.jpg",
      "https://i.postimg.cc/pd9y5p1F/B1层主卧衣柜_写字台梳妆台.jpg",
      "https://i.postimg.cc/XvXBK2Xs/B1层卫生间_1.png",
      "https://i.postimg.cc/FK1kbP1W/B1层卫生间_2.png",
      "https://i.postimg.cc/R086gcHx/B1层卫生间_3.png",
      "https://i.postimg.cc/nL5j3vQN/B1层卫生间_4.png",
      "https://i.postimg.cc/W1Yh4MSN/B1层卫生间_5.png",
      "https://i.postimg.cc/7ZtfLgXY/B1层卫生间_6.png",
      "https://i.postimg.cc/W1Yh4MSG/B1层卫生间_7.png",
      "https://i.postimg.cc/YCDhS18Q/B1层卫生间_8.png",
      "https://i.postimg.cc/yYz9qXpw/B1层客房.jpg",
      "https://i.postimg.cc/HsC5G4vF/B1层客房_2.jpg",
      "https://i.postimg.cc/zfL3HVPw/B1层走廊.jpg",
      "https://i.postimg.cc/8CFsfjnb/B1层走廊与楼梯之间玻璃门.jpg",
      "https://i.postimg.cc/CKZdnz6H/B1层走廊通往卫生间.jpg",
      "https://i.postimg.cc/Fs9RgPB9/一层厨房.png",
      "https://i.postimg.cc/159tcWjR/一层厨房_2.png",
      "https://i.postimg.cc/QxXtk6yM/一层厨房_3.png",
      "https://i.postimg.cc/BQMvhxrH/一层客厅.png",
      "https://i.postimg.cc/8PtCyh2y/一层客厅_2.png",
      "https://i.postimg.cc/J4PhTbf5/一层客厅壁炉背景墙.png",
      "https://i.postimg.cc/wjrjz9Ty/一层客厅楼梯.png",
      "https://i.postimg.cc/SsFQXV94/一层楼梯_入口.png",
      "https://i.postimg.cc/gJFcw4hL/一层楼梯下方储藏室.png",
      "https://i.postimg.cc/4dk4Kwc9/一层楼梯通往二层.png",
      "https://i.postimg.cc/x8905Cgg/一层露台_洗衣机柜_折叠门.png",
      "https://i.postimg.cc/3RX82pjJ/一层露台带跑步机.png",
      "https://i.postimg.cc/6qB9c3Y6/一层露台洗衣机柜.png",
      "https://i.postimg.cc/x8PdVHc8/一层餐厅.png",
      "https://i.postimg.cc/HntL15Vj/一层餐厅_2.png",
      "https://i.postimg.cc/c17C3qTD/一层餐厅备餐柜.png",
      "https://i.postimg.cc/4NJdb8Ss/一层餐厅备餐柜_2.png",
      "https://i.postimg.cc/KYdjPx6x/二层儿子房间.jpg",
      "https://i.postimg.cc/yNwxmsMY/二层儿子房间_2.jpg",
      "https://i.postimg.cc/ydcdn2K0/二层儿子房间卫生间.png",
      "https://i.postimg.cc/0QDQZhvd/二层儿子房间卫生间_2.png",
      "https://i.postimg.cc/rmxmg7T9/二层儿子房间卫生间_3.png",
      "https://i.postimg.cc/1zLXGskX/二层儿子房间开放衣柜.jpg",
      "https://i.postimg.cc/9fv0dC6H/二层儿童房_1.png",
      "https://i.postimg.cc/k5kGQq09/二层儿童房_2.png",
      "https://i.postimg.cc/tgLJ3pKq/二层儿童房_3.png",
      "https://i.postimg.cc/ydcdn2Kk/二层小客厅.jpg",
      "https://i.postimg.cc/nrxLWTVR/二层小客厅_2.png",
      "https://i.postimg.cc/qqG7Hnzh/二层小客厅_3.png",
      "https://i.postimg.cc/rpvs1Mv3/地下一层到一层楼梯.png"
    ]
  },
  {
    id: 10,
    title: "Compact Studio Living",
    title_zh: "小户型全屋定制",
    category: "Customization",
    description: "Maximizing 35sqm of space with intelligent custom cabinetry and fold-away furniture solutions.",
    location: "Rome, Italy",
    year: "2022",
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop",
    gallery: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1470&auto=format&fit=crop"]
  },
  // 13. Sushi Ten Outdoor Area Renovation (Middle-Back Placement)
  {
    id: 20,
    title: "Sushi Ten Outdoor Area Renovation",
    title_zh: "Sushi Ten 户外区域改造",
    category: "Commercial",
    description: "A renovation project for the outdoor dining area of Sushi Ten in Italy. The design transforms the open outdoor space into a private, Zen-inspired dining sanctuary through the strategic use of wooden lattices, enclosed seating, and lush landscaping. The curated lighting and material palette create a serene urban oasis.",
    description_zh: "2023年进行的Sushi Ten餐厅户外区域改造项目。设计师利用日式和风美学，通过定制的木质围挡、舒适的半开放式软装以及氛围照明，提升了户外空间的用餐舒适度与视觉辨识度。项目不仅解决了户外空间利用率的问题，更为品牌注入了自然与宁静的设计灵魂。",
    location: "Italy",
    year: "2023",
    imageUrl: "https://i.postimg.cc/mhxwzP4c/9.jpg",
    gallery: [
      "https://i.postimg.cc/mhxwzP4c/9.jpg",
      "https://i.postimg.cc/zfp0tDCM/1.jpg",
      "https://i.postimg.cc/8s8HJ7G6/10.jpg",
      "https://i.postimg.cc/bdXTDZPn/11.jpg",
      "https://i.postimg.cc/5tpn79BR/2.jpg",
      "https://i.postimg.cc/mrV8XZY0/3.jpg",
      "https://i.postimg.cc/JhKP673V/4.jpg",
      "https://i.postimg.cc/0QBZvtHC/5.jpg",
      "https://i.postimg.cc/hvQst9kg/6.jpg",
      "https://i.postimg.cc/rsRjwSBX/7.jpg",
      "https://i.postimg.cc/nM8kjXxz/8.jpg"
    ]
  },
  // 14. Tuscany Montecatini Korean BBQ
  {
    id: 17,
    title: "Tuscany Montecatini Korean BBQ",
    title_zh: "托斯卡纳montecatini韩式烤肉馆",
    category: "Commercial",
    description: "A specialized restaurant design project in Montecatini Terme, Tuscany, bringing the authentic atmosphere of Korean barbecue to the heart of Italy. The design features industrial-inspired exhaust systems integrated into a warm, wood-textured interior, creating a unique cross-cultural dining environment. Every detail, from the specialized grilling tables to the atmospheric lighting, is crafted to provide an immersive and social dining experience.",
    description_zh: "位于意大利托斯卡纳蒙特卡蒂尼（Montecatini Terme）的特色餐饮设计项目。该项目将地道的韩式烤肉氛围带入意大利。设计将工业风的排烟系统巧妙融入温润的木质感内饰中，打造出一个独特的跨文化就餐环境。从专业的烤肉台到极具氛围感的灯光设计，每一个细节都旨在为食客提供沉浸式的社交用餐体验。",
    location: "Montecatini Terme, Italy",
    year: "2024",
    imageUrl: "https://i.postimg.cc/DwHrpWHm/10.jpg",
    gallery: [
      "https://i.postimg.cc/DwHrpWHm/10.jpg",
      "https://i.postimg.cc/T3pjcj7M/1.jpg",
      "https://i.postimg.cc/P59WVL98/11.jpg",
      "https://i.postimg.cc/Z528s923/12.jpg",
      "https://i.postimg.cc/T3FVNyFg/13.jpg",
      "https://i.postimg.cc/mgJYpcJY/14.jpg",
      "https://i.postimg.cc/JzvNYyvQ/15.jpg",
      "https://i.postimg.cc/MGByC6JQ/16.jpg",
      "https://i.postimg.cc/Xv5wRj6F/17.jpg",
      "https://i.postimg.cc/fbdxGzQY/18.jpg",
      "https://i.postimg.cc/zfhnszYn/19.jpg",
      "https://i.postimg.cc/5265m57W/2.jpg",
      "https://i.postimg.cc/g0hvCzbV/20.jpg",
      "https://i.postimg.cc/q7K8PJHQ/21.jpg",
      "https://i.postimg.cc/PqDmgXn2/22.jpg",
      "https://i.postimg.cc/bvnQ7yfm/23.jpg",
      "https://i.postimg.cc/pdjDwWM0/24.jpg",
      "https://i.postimg.cc/d0C8bscX/25.jpg",
      "https://i.postimg.cc/g2nyKySP/3.jpg",
      "https://i.postimg.cc/Dw8QcQjT/4.jpg",
      "https://i.postimg.cc/2SVdxdcS/5.jpg",
      "https://i.postimg.cc/BnX5C5Yv/6.jpg",
      "https://i.postimg.cc/zG6C2L6Y/7.jpg",
      "https://i.postimg.cc/cL2RkK2N/8.jpg",
      "https://i.postimg.cc/VkpqZSpm/9.jpg"
    ]
  }
];
